var express = require('express');
var router = express.Router();
var mysql = require('mysql');
var compression = require('compression')


var connection = mysql.createConnection({
	host: 'localhost',
	user: 'root',
	password: 'root',
	database: 'bittrex_data'
})

// Load Handlebars 
var Handlebars = require('handlebars');
// Load the package 
var H = require('just-handlebars-helpers');
 
// Register helpers for Handlebars 
H.registerHelpers(Handlebars);

Handlebars.registerHelper("divide", function(thing1, thing2) {
  return thing1 / thing2 ;
});



Handlebars.registerHelper("toFixed", function(number, digits) {
  return Number((number).toFixed(digits));
});


router.get('/', function(req, res, next){
	var all_rows = [];
	var max = 11000;
	var couter = 0;
	var inner_couter = 0;
	res.flush()
	connection.query("SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_SCHEMA = 'bittrex_data';", function(err, rows, fields){
		if(err) throw err;
		max = rows.length;
	 	for(var i = 0; i < rows.length;i++){
			connection.query("SELECT '" + rows[i].TABLE_NAME + "' as Market," + 
							 "ROUND(SUM(IF(OrderType='BUY' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 1440 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=0 , Total, 0)), 4) as Buy_d1,  ROUND(SUM(IF(OrderType='SELL' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 1440 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=0, Total, 0)), 4) as Sell_d1, ROUND((SUM(IF(OrderType='BUY' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 1440 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=0 , Total, 0)) - SUM(IF(OrderType='SELL' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 1440 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=0 , Total, 0))), 4) as Over_d1, SUM(IF(OrderType = 'BUY' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 1440 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=0 , 1, 0)) AS NUMS_BUY_ORDER_d1, SUM(IF(OrderType = 'SELL'  AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 1440 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=0 , 1, 0)) AS NUMS_SELL_ORDER_d1, MIN(IF(TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 1440 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=0, Price, 100000)) AS LOWEST_PRICE_d1, MAX(IF(TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 1440 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=0, Price, 0)) AS HIGHEST_PRICE_d1, " +
							 "ROUND(SUM(IF(OrderType='BUY' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 2880 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=1440 , Total, 0)), 4) as Buy_d2,  ROUND(SUM(IF(OrderType='SELL' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 2880 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=1440, Total, 0)), 4) as Sell_d2, ROUND((SUM(IF(OrderType='BUY' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 2880 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=1440 , Total, 0)) - SUM(IF(OrderType='SELL' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 2880 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=1440 , Total, 0))), 4) as Over_d2, SUM(IF(OrderType = 'BUY' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 2880 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=1440 , 1, 0)) AS NUMS_BUY_ORDER_d2, SUM(IF(OrderType = 'SELL'  AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 2880 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=1440 , 1, 0)) AS NUMS_SELL_ORDER_d2, MIN(IF(TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 2880 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=1440, Price, 100000)) AS LOWEST_PRICE_d2, MAX(IF(TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 2880 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=1440, Price, 0)) AS HIGHEST_PRICE_d2, " +
							 "ROUND(SUM(IF(OrderType='BUY' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 4320 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=2880 , Total, 0)), 4) as Buy_d3,  ROUND(SUM(IF(OrderType='SELL' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 4320 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=2880, Total, 0)), 4) as Sell_d3, ROUND((SUM(IF(OrderType='BUY' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 4320 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=2880 , Total, 0)) - SUM(IF(OrderType='SELL' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 4320 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=2880 , Total, 0))), 4) as Over_d3, SUM(IF(OrderType = 'BUY' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 4320 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=2880 , 1, 0)) AS NUMS_BUY_ORDER_d3, SUM(IF(OrderType = 'SELL'  AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 4320 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=2880 , 1, 0)) AS NUMS_SELL_ORDER_d3, MIN(IF(TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 4320 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=2880, Price, 100000)) AS LOWEST_PRICE_d3, MAX(IF(TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 4320 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=2880, Price, 0)) AS HIGHEST_PRICE_d3, " +
							 "ROUND(SUM(IF(OrderType='BUY' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 5760 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=4320 , Total, 0)), 4) as Buy_d4,  ROUND(SUM(IF(OrderType='SELL' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 5760 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=4320, Total, 0)), 4) as Sell_d4, ROUND((SUM(IF(OrderType='BUY' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 5760 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=4320 , Total, 0)) - SUM(IF(OrderType='SELL' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 5760 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=4320 , Total, 0))), 4) as Over_d4, SUM(IF(OrderType = 'BUY' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 5760 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=4320 , 1, 0)) AS NUMS_BUY_ORDER_d4, SUM(IF(OrderType = 'SELL'  AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 5760 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=4320 , 1, 0)) AS NUMS_SELL_ORDER_d4, MIN(IF(TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 5760 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=4320, Price, 100000)) AS LOWEST_PRICE_d4, MAX(IF(TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 5760 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=4320, Price, 0)) AS HIGHEST_PRICE_d4, " +
							 "ROUND(SUM(IF(OrderType='BUY' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 7200 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=5760 , Total, 0)), 4) as Buy_d5,  ROUND(SUM(IF(OrderType='SELL' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 7200 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=5760, Total, 0)), 4) as Sell_d5, ROUND((SUM(IF(OrderType='BUY' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 7200 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=5760 , Total, 0)) - SUM(IF(OrderType='SELL' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 7200 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=5760 , Total, 0))), 4) as Over_d5, SUM(IF(OrderType = 'BUY' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 7200 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=5760 , 1, 0)) AS NUMS_BUY_ORDER_d5, SUM(IF(OrderType = 'SELL'  AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 7200 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=5760 , 1, 0)) AS NUMS_SELL_ORDER_d5, MIN(IF(TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 7200 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=5760, Price, 100000)) AS LOWEST_PRICE_d5, MAX(IF(TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 7200 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=5760, Price, 0)) AS HIGHEST_PRICE_d5, " +
							 "ROUND(SUM(IF(OrderType='BUY' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 8640 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=7200 , Total, 0)), 4) as Buy_d6,  ROUND(SUM(IF(OrderType='SELL' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 8640 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=7200, Total, 0)), 4) as Sell_d6, ROUND((SUM(IF(OrderType='BUY' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 8640 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=7200 , Total, 0)) - SUM(IF(OrderType='SELL' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 8640 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=7200 , Total, 0))), 4) as Over_d6, SUM(IF(OrderType = 'BUY' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 8640 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=7200 , 1, 0)) AS NUMS_BUY_ORDER_d6, SUM(IF(OrderType = 'SELL'  AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 8640 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=7200 , 1, 0)) AS NUMS_SELL_ORDER_d6, MIN(IF(TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 8640 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=7200, Price, 100000)) AS LOWEST_PRICE_d6, MAX(IF(TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 8640 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=7200, Price, 0)) AS HIGHEST_PRICE_d6, " +
							 "ROUND(SUM(IF(OrderType='BUY' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 10080 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=8640 , Total, 0)), 4) as Buy_d7,  ROUND(SUM(IF(OrderType='SELL' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 10080 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=8640, Total, 0)), 4) as Sell_d7, ROUND((SUM(IF(OrderType='BUY' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 10080 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=8640 , Total, 0)) - SUM(IF(OrderType='SELL' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 10080 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=8640 , Total, 0))), 4) as Over_d7, SUM(IF(OrderType = 'BUY' AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 10080 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=8640 , 1, 0)) AS NUMS_BUY_ORDER_d7, SUM(IF(OrderType = 'SELL'  AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 10080 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=8640 , 1, 0)) AS NUMS_SELL_ORDER_d7, MIN(IF(TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 10080 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=8640, Price, 100000)) AS LOWEST_PRICE_d7, MAX(IF(TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 10080 AND TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) >=8640, Price, 0)) AS HIGHEST_PRICE_d7 " +
							 " FROM " + rows[i].TABLE_NAME + 
							 " WHERE TIMESTAMPDIFF(MINUTE,TimeStamp,UTC_TIMESTAMP()) < 10080", function(err, row, fields){
													if(err) throw err;
												 	for(var i = 0; i < row.length;i++){
											        	all_rows.push(row[i]);
											        	if (i == row.length - 1){
											        		couter++;
											        	}
											  		}

				if (couter == rows.length){
					console.log('In here');
					// couter = 0;

					res.render('frame1d', {
						"projects":  all_rows
					});
					return;
				}
										
			});
		}
	});

});

module.exports = router;
